/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package genak

import kotlinx.coroutines.experimental.runBlocking
import org.slf4j.LoggerFactory
import org.testng.annotations.Test

class AppTest {
    val log = LoggerFactory.getLogger(this.javaClass.name)

    @Test
    fun tst() = runBlocking {

        val (result, totalTime) = time {
            spawn(1_000_000) { timestamp() }.map { it.await() }
        }

        val zeroMsCount = result.filter { it.second.elapsedMs == 0L }.count()

        log.info("totalTime {}, zeroMsCount {}", totalTime, zeroMsCount)
    }

}
