/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package genak

import kotlinx.coroutines.experimental.*
import kotlinx.coroutines.experimental.channels.Channel
import org.testng.annotations.Test
import kotlin.system.measureTimeMillis


class PongChannelTest : PongBase() {


    @Test
    fun channelTest() = runBlocking {
        log.info("begin")
        val total = 100_000
        val totalTime = measureTimeMillis {
            val channel = Channel<Deferred<Pair<FuelRes, Timings>>>(1000)

            launch(Dispatchers.Unconfined) {
                for (i in 1..total) {
                    channel.send(
                            async(CoroutineName("send$i")) {
                                time {
                                    logProgressPart(i, total, "wget", 10)
                                    wget(promisedCount.getAndIncrement())
                                }
                            }
                    )

                }
            }

            launch(Dispatchers.Unconfined + CoroutineName("reaper")) {
                for (i in 1..total) {
                    val promise = channel.receive()
                    logProgressPart(i, total, "fulfilled", 10)

                    val fulfilled = promise.await()
                    measurement(fulfilled, "qwert02").reportHttp()
                }
            }.join()
            channel.cancel()
            channel.close()
        }
        log.info("totalCount {} totalTime {} msec, rate {} rps ", total, totalTime, total / (totalTime / 1000))
    }
}
