/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package genak

import kotlinx.coroutines.experimental.runBlocking
import org.testng.annotations.Test
import kotlin.system.measureTimeMillis


class PongListTest : PongBase() {


    @Test
    fun listTest() = runBlocking {
        log.info("begin")
        val total = 1_000_000
        val totalTime = measureTimeMillis {

            val (promises, promisesMs) = time {
                spawnList(total) {
                    wget(id.getAndIncrement())
                }
            }

            val (fulfilled, fulfilledMs) = time {
                promises.map {
                    it.await()
                }
            }

            val (_, reportMs) = time {
                fulfilled.forEach {
                    measurement(it).reportHttp()
                }
            }

            val reportOverhead = 100 * reportMs.elapsedMs / fulfilledMs.elapsedMs
            log.info("promisesMs {} fulfilledMs {}, reportMs {} ({}%)", promisesMs.elapsedMs, fulfilledMs.elapsedMs, reportMs.elapsedMs, reportOverhead)
        }
        log.info("totalCount {} totalTime {} msec, rate {} rps ", total, totalTime, total / (totalTime / 1000))
    }
}
