---
version: "2"
services:
  pong:
    image: "ludenus/pong:0.0.1"
    ports:
    - "8100:80"
    environment:
      PONG_LISTENING_ADDRESS: ":80"

  grafana:
    image: "grafana/grafana:5.3.0"
    ports:
    - "3100:3000"
    volumes:
#    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "********"

  influxdb:
    image: "influxdb:1.6.3"
    volumes:
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
    - "8186:8086"
    - "8189:8089/udp" # udp
    - "8183:8083"
    - "2103:2003"

    environment:
      INFLUXDB_DB: "qadb"
#      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_USER: "dbuser"
      INFLUXDB_USER_PASSWORD: "********"

  heartbeat:
    build: heartbeat/
    environment:
      INFLUX_DB_URL: "http://influxdb:8086"
      INFLUX_DB_NAME: "qadb"

  tsung:
    build: tsung/
    image: tsung:1.7.0
    ports:
    - "8191:8091"
    volumes:
    - ./tsung/tsung.xml:/root/.tsung/tsung.xml:ro
    depends_on:
    - pong


